[build]   
  functions = "functions"
[[redirects]]
  from = "/metadata/:tokenId"
  to = "/functions/metadata?tokenId=:tokenId"
  force = true
  query = {tokenId = ":tokenId"}
  status = 200
[[redirects]]
  from = "/"
  to = "/functions/metadata"