[build]   
  functions = "/.netlify/functions"
[[redirects]]
  from = "/metadata/:tokenId"
  to = "/.netlify/functions/metadata?tokenId=:tokenId"
  force = true
  query = {tokenId = ":tokenId"}
  status = 200
[[redirects]]
  from = "/"
  to = "/.netlify/functions/metadata"